
models = [
    #{
    #    "name": "logistic_regression",
    #    "scaler_path": "model_data/logistic_regression_scaler.p",
    #    "model_path": "model_data/logistic_regression_model.p",
    #    "features": ["Batting Average", "On-Base%", "Slugging %", "Average Home Runs", "Average Runs Batted In", "At Bats Per Game"],
    #},
    #{
    #    "name": "logistic_regression",
    #    "scaler_path": "model_data/logistic_regression_2_scaler.p",
    #    "model_path": "model_data/logistic_regression_2_model.p",
    #    "features": ["Batting Average",
    #                 "On-Base%",
    #                 "Slugging %",
    #                 "Average Home Runs",
    #                 "Average Runs Batted In",
    #                 "At Bats Per Game",
    #                 "Games Played",
    #                 "Last Season Batting Average",
    #                 "Last Season On-Base%",
    #                 "Last Season Slugging %",
    #                 "Last Season Average Home Runs",
    #                 "Last Season Average Runs Batted In",
    #                 "Last Season At Bats Per Game"]
    #},
    {
        "name": "logistic_regression",
        "scaler_path": "model_data/20240507logistic_regression_with_pitcher_data_scaler.p",
        "model_path": "model_data/20240507logistic_regression_with_pitcher_data_model.p",
        "features": ["Batting Average",
                     "On-Base%",
                     "Slugging %",
                     "Home Runs",
                     "Runs Batted In",
                     "Hits",
                     "Runs Scored",
                     "Average Home Runs",
                     "Average Runs Batted In",
                     "Average Hits",
                     "Average Runs Scored",
                     "At Bats Per Game",
                     "Games Played",
                     "Last Season Batting Average",
                     "Last Season On-Base%",
                     "Last Season Slugging %",
                     "Last Season Home Runs",
                     "Last Season Runs Batted In",
                     "Last Season Hits",
                     "Last Season Runs Scored",
                     "Last Season Average Home Runs",
                     "Last Season Average Runs Batted In",
                     "Last Season Average Hits",
                     "Last Season Average Runs Scored",
                     "Last Season At Bats Per Game",
                     "Opposing Pitcher Earned Run Average",
                     "Opposing Pitcher Innings Pitched",
                     "Opposing Pitcher Hits",
                     "Opposing Pitcher Runs Scored",
                     "Opposing Pitcher Earned Runs",
                     "Opposing Pitcher Bases on Balls",
                     "Opposing Pitcher Strikeouts",
                     "Opposing Pitcher Home Runs",
                     "Opposing Pitcher Games Played",
                     "Opposing Pitcher Batters Faced",
                     "Opposing Pitcher Innings Pitched Per Game",
                     "Opposing Pitcher Average Hits",
                     "Opposing Pitcher Average Runs Scored",
                     "Opposing Pitcher Average Earned Runs",
                     "Opposing Pitcher Average Bases on Balls",
                     "Opposing Pitcher Average Home Runs",
                     "Opposing Pitcher Average Strikeouts",
                     "Opposing Pitcher Last Season Earned Run Average",
                     "Opposing Pitcher Last Season Innings Pitched",
                     "Opposing Pitcher Last Season Hits",
                     "Opposing Pitcher Last Season Runs Scored",
                     "Opposing Pitcher Last Season Earned Runs",
                     "Opposing Pitcher Last Season Bases on Balls",
                     "Opposing Pitcher Last Season Strikeouts",
                     "Opposing Pitcher Last Season Home Runs",
                     "Opposing Pitcher Last Season Games Played",
                     "Opposing Pitcher Last Season Batters Faced",
                     "Opposing Pitcher Last Season Innings Pitched Per Game",
                     "Opposing Pitcher Last Season Average Hits",
                     "Opposing Pitcher Last Season Average Runs Scored",
                     "Opposing Pitcher Last Season Average Earned Runs",
                     "Opposing Pitcher Last Season Average Bases on Balls",
                     "Opposing Pitcher Last Season Average Home Runs",
                     "Opposing Pitcher Last Season Average Strikeouts"]
    },
]
